module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/tests'],
  testMatch: ['**/*.test.ts'],
  moduleNameMapper: {
    '^@app/(.*)$': '<rootDir>/src/app/$1',
    '^@auth/(.*)$': '<rootDir>/src/auth/$1',
    '^@mqtt/(.*)$': '<rootDir>/src/mqtt/$1',
    '^@modbus/(.*)$': '<rootDir>/src/modbus/$1',
    '^@http/(.*)$': '<rootDir>/src/http/$1',
    '^@communication/(.*)$': '<rootDir>/src/communication/$1',
    '^@database/(.*)$': '<rootDir>/src/database/$1',
    '^@graphics/(.*)$': '<rootDir>/src/graphics/$1',
    '^@workouts/(.*)$': '<rootDir>/src/workouts/$1',
    '^@admin/(.*)$': '<rootDir>/src/admin/$1',
    '^@tags/(.*)$': '<rootDir>/src/tags/$1',
    '^@websocket/(.*)$': '<rootDir>/src/websocket/$1',
    '^@utils/(.*)$': '<rootDir>/src/utils/$1',
  },
};
